services:
  postgres:
    image: postgres:latest
    container_name: jimine-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file: .env
    healthcheck:
      test: "exit 0"
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    networks:
      - jimine-local
    #    volumes:
    #      - jimine-volume:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: jimine-redis
    restart: unless-stopped
    ports:
      - 6379:6379
#    volumes:
#      - redis_volume:/data
    networks:
      - jimine-local

networks:
  jimine-local:
    name: jimine-local
    driver: bridge
#volumes:
#  jimine-volume:



#  keycloak:
#    image: keycloak/keycloak:latest
#    restart: unless-stopped
#    command: start-dev --verbose
#    container_name: keycloakc
#    ports:
#      - "8080:8080" # Don't change!
#    env_file: .env
#    environment:
#      KC_DB_URL: ${POSTGRESQL_URL_HOST}
#      KC_DB: postgres`
#      KC_DB_SCHEMA: ${POSTGRESQL_SCHEMA}
#      KC_DB_USERNAME: ${POSTGRESQL_USER}
#      KC_DB_PASSWORD: ${POSTGRESQL_PASSWORD}
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    networks:
#      - jimine-local
#    depends_on:
#      - postgres